# Generated by Django 3.1.2 on 2022-02-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20220208_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measure', to='measurement.sensor'),
        ),
        migrations.DeleteModel(
            name='SensorMeasurement',
        ),
    ]
