# Generated by Django 3.1.2 on 2022-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20220211_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor_id',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor_id',
            field=models.ManyToManyField(related_name='measure', to='measurement.Sensor'),
        ),
    ]
