# Generated by Django 3.1.2 on 2022-02-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_auto_20220211_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
